name: Make multiarch image

on:
  registry_package:
    types: [updated]

jobs:
  make:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u lourkeur --password-stdin
      - name: Make the multiarch image
        # Using Podman because Docker balks at OCI images
        run: |
          podman manifest create hostapd-mana \
            ghcr.io/lourkeur/hostapd-mana.docker:latest-x86_64-linux \
            ghcr.io/lourkeur/hostapd-mana.docker:latest-aarch64-linux
      - name: Publish the multiarch image
        run: |
          podman manifest push hostapd-mana ghcr.io/lourkeur/hostapd-mana.docker:latest
